<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>peplink_router_driver</name>
  <version>0.0.2</version>
  <description>ROS 2 driver for Peplink mobile routers</description>
  <maintainer email="civerachb@clearpathrobotics.com">Chris Iverach-Brereton</maintainer>
  <license>BSD</license>

  <author email="civerachb@clearpathrobotics.com">Chris Iverach-Brereton</author>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <exec_depend>diagnostic_msgs</exec_depend>
  <exec_depend>diagnostic_updater</exec_depend>
  <exec_depend>peplink_msgs</exec_depend>
  <exec_depend>python3-requests</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>wireless_msgs</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
