string name
string led_color
string message
string type
string virtual_type
string gateway
string mac
string ip_address
string method
string mode
string routing_mode
string[] dns
string[] additional_ip

bool as_lan
bool enable
bool locked
bool scheduled_off

int32 uptime
int32 priority
int32 group_set
int32 mtu
int32 mss
int32 netmask

wireless_msgs/Connection wireless
peplink_msgs/Modem modem
peplink_msgs/Gobi cellular
peplink_msgs/Gobi gobi
peplink_msgs/BandwidthAllowance allowance
